blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Better Bravo Lights Documentation
    url: https://github.com/RoystonS/BetterBravoLights/wiki
    about: Full documentation for using and configuring Better Bravo Lights